language: c
compiler:
  - gcc

before_script:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update -qq
  #[OPENCOM-ONLY]#- sudo apt-get install -y python3.4 python3 gcc-4.7 gcc-multilib gcc-arm-none-eabi qemu-system mingw32
  - sudo apt-get install -y python3.4 python3 gcc-4.7 gcc-multilib
  # For teensy build
  - sudo apt-get install realpath
  # For coverage testing
  - sudo pip install cpp-coveralls

script:
  - make -C opencom
